AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Sample SAM Template for books-api

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10
    MemorySize: 128

Resources:
  BooksApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: books-api
      #MethodSettings:
      #  - LoggingLevel: INFO
      #    ResourcePath: '/*' # allows for logging on any resource
      #    HttpMethod: '*' # allows for logging on any method      
      StageName: Prod
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters: 
            Location: ../API-Definition/openapi.yaml

  #BookstoreFunction:
  GetBooksFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ./src/Bookstore/
      Handler: Bookstore::Bookstore.Function::GetBooks
      Runtime: dotnet6
      Architectures:
        - x86_64
      MemorySize: 256
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE
      Events:
        Bookstore:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:          
            Path: /books
            Method: GET
            RestApiId: !Ref BooksApi
          
  GetSingleBookFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ./src/Bookstore/
      Handler: Bookstore::Bookstore.Function::GetBookById
      Runtime: dotnet6
      Architectures:
        - x86_64
      MemorySize: 256
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE
      Events:
        Bookstore:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:          
            Path: /books/{id}
            Method: GET
            RestApiId: !Ref BooksApi

  CreateOrderFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ./src/Bookstore/
      Handler: Bookstore::Bookstore.Function::CreateOrder
      Runtime: dotnet6
      Architectures:
        - x86_64
      MemorySize: 256
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE
      Events:
        Bookstore:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:          
            Path: /orders
            Method: POST
            RestApiId: !Ref BooksApi  

  GetOrderFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ./src/Bookstore/
      Handler: Bookstore::Bookstore.Function::GetOrderById
      Runtime: dotnet6
      Architectures:
        - x86_64
      MemorySize: 256
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE
      Events:
        Bookstore:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:          
            Path: /orders/{orderId}
            Method: GET
            RestApiId: !Ref BooksApi      

  UpdateOrderFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ./src/Bookstore/
      Handler: Bookstore::Bookstore.Function::UpdateOrderById
      Runtime: dotnet6
      Architectures:
        - x86_64
      MemorySize: 256
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE
      Events:
        Bookstore:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:          
            Path: /orders/{orderId}
            Method: PUT
            RestApiId: !Ref BooksApi  

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  #BookstoreApi:
  #  Description: "API Gateway endpoint URL for Prod stage for Bookstore function"
  #  Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/books/"
  BookstoreApi:
    Description: "API Gateway endpoint URL for Prod stage for Bookstore function"
    Value: !Sub "https://${BooksApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"    
  GetBooksFunction:
    Description: "Bookstore Lambda Function ARN"
    Value: !GetAtt GetBooksFunction.Arn
  GetBooksFunctionIamRole:
    Description: "Implicit IAM Role created for Bookstore function"
    Value: !GetAtt GetBooksFunction.Arn
